heat_template_version: 2013-05-23

description: HOT template to create one tenant network

parameters:

  image:
    type: string
    default: cirros-0.3.4-x86_64-uec

  flavor:
    type: string
    default: m1.tiny

resources:

  network1:
    type: OS::Neutron::Net
    properties:
       name: net2

  subnet1:
    type: OS::Neutron::Subnet
    properties:
       network_id: {Ref: network1}
       name: subnet2
       ip_version: 4
       cidr: 192.168.2.0/24
       allocation_pools:
       - {end: 192.168.2.100, start: 192.168.2.50}
